### ISSUE TITLE
`brew add` adds tap of `core` that is no longer needed

### ISSUE THREAD

**Issue by ian-h-chamberlain** [superatomic/homebrew-bundle-extensions#12]
`brew add` appears to always add the `core` tap, which I guess is deprecated now?

```console
$ touch bundle
$ brew add lnav --file bundle
==> Using Brewfile at '/Users/ianchamberlain/Downloads/bundle'
==> Added Tap homebrew/core to Brewfile
==> Added Formula lnav to Brewfile
$ brew bundle install --file bundle
Tapping homebrew/core
Error: Tapping homebrew/core is no longer typically necessary.
Add --force if you are sure you need it done.
Tapping homebrew/core has failed!
==> Downloading https://formulae.brew.sh/api/formula.jws.json

Using lnav
Homebrew Bundle failed! 1 Brewfile dependency failed to install.
$ 
```

Maybe the `core` tap could be special-cased to avoid being added, since it will cause subsequent installs from that file to fail without `--force`.

**Comment by superatomic** [comment]
Thank you for bringing this to my attention!

I was able to reproduce this issue after running `brew untap homebrew/core`, which surprisingly doesn't break any of my Homebrew packages (I have no clue when this change was made or where the Formula are being read from without the tap). Regardless, it does seem that a simple special case for `core` will resolve this issue. I'm going to quickly check that no other taps behave like this (mainly `homebrew/cask`) and then I'll write and push a fix.

**Comment by superatomic** [comment]
@ian-h-chamberlain this should all be resolved now, but I'd appreciate it if you could confirm. Run `brew update` (and `brew untap homebrew/core` if necessary) and let me know if the issue persists.

**Comment by ian-h-chamberlain** [comment]
Thanks for the quick turnaround! Looks like it's working for me too.
