### ISSUE TITLE
Drop Casks does not work

### ISSUE THREAD

**Issue by boldandbrad** [superatomic/homebrew-bundle-extensions#8]
When running `brew drop equinox` or `brew drop --cask equinox` (or any other cask) I get the following error:

```
Error: no implicit conversion of Array into String
/usr/local/Homebrew/Library/Homebrew/formulary.rb:217:in `exist?'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:217:in `resolve'
/usr/local/Homebrew/Library/Taps/superatomic/homebrew-bundle-extensions/cmd/drop.rb:67:in `block in drop'
/usr/local/Homebrew/Library/Taps/superatomic/homebrew-bundle-extensions/cmd/drop.rb:57:in `each'
/usr/local/Homebrew/Library/Taps/superatomic/homebrew-bundle-extensions/cmd/drop.rb:57:in `drop'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

Line 67 in drop is the culprit:

`brew_name_resolves_to_full_name = Formulary.resolve(brew.name).full_name == brew.full_name`

Although this works wonderfully to avoid formulae conflicts, this does not work for casks. A slight oversight. 

@superatomic are you aware of a similar function to `Formulary.resolve` that exists for Casks? If there isn't one, we could only perform the check for formulae and move on.

Let me know what you think.

**Comment by superatomic** [comment]
Oops! I didn't even think to test whether casks worked with `brew drop`. That's my bad.

I'm sure that their must be some equivalent method to `Formulary.resolve` for casks, although I haven't looked through Homebrew's source code for it yet. I'll take a look and let you know what I find.

Finally, thanks for the helpful bug report!

**Comment by superatomic** [comment]
I'm not going to be able to access a computer today. I'll try to get a fix out as soon as I can. Apologies for the delay!

**Comment by superatomic** [comment]
It looks like [`Cask::CaskLoader.load`](https://github.com/Homebrew/brew/blob/0d6d390c5cff114f23cf207c5dc0436296a13977/Library/Homebrew/cask/cask_loader.rb#L204) is the equivalent of `Formulary.resolve` for casks.

Additionally, to get the short name of a cask, `brew.token` needs to be used instead of `brew.name`, because `brew.name` an array of a cask's display names instead of it's actual name (but for _formulae_ `brew.name` refers to the correct value).

**Comment by superatomic** [comment]
Sorry for the delay! The problem should be fixed now, just run `brew update`, and the command `brew drop equinox` (and other uses of `brew drop` that remove casks) should successfully run without errors.

**Comment by boldandbrad** [comment]
No worries at all! Thanks for the quick support!
